#!/bin/sh
USAGE="usage: $0 [--daemon] [--testnet]"
[ "$#" -eq 1 ] && [ "$1" != "--daemon" ] && [ "$1" != "--testnet" ] && echo $USAGE && exit 1
[ "$#" -eq 2 ] && ([ "$1" != "--daemon" ] || [ "$2" != "--testnet" ]) && echo $USAGE && exit 1
[ "$#" -gt 2 ] && echo $USAGE && exit 1
DAEMON=$([ "$1" = "--daemon" ] && echo "-d --restart unless-stopped" || echo "-it --rm")
([ "$1" = "--testnet" ] || [ "$2" = "--testnet" ]) && TESTNET="t"
FOLDER=$(dirname "$(readlink -f "$0")")
docker build -q -t bitcoin:0.26.0 $FOLDER > /dev/null || exit 1
mkdir -p $FOLDER/datadir/bitcoin/ $FOLDER/datadir/blockbook/ $FOLDER/datadir/onion/
chmod -f 700 $FOLDER/datadir/onion/
rm -f $FOLDER/datadir/bitcoin/onion_v3_private_key $FOLDER/datadir/bitcoin/testnet3/onion_v3_private_key
docker run $DAEMON --dns 0.0.0.0 --name $TESTNET"bitcoin" --hostname $TESTNET"bitcoin" -v $FOLDER/datadir/:/home/ubuntu/datadir/ -e TESTNET=$TESTNET bitcoin:0.26.0
