#!/bin/sh
USAGE="usage: $0 [--testnet]"
[ "$#" -eq 1 ] && [ "$1" != "--testnet" ] && echo $USAGE && exit 1
[ "$#" -gt 1 ] && echo $USAGE && exit 1
[ "$1" = "--testnet" ] && TESTNET="t"
docker inspect $TESTNET"bitcoin" > /dev/null || exit 1
docker stop -t 60 $TESTNET"bitcoin" > /dev/null &
docker exec $TESTNET"bitcoin" pkill supervisord
wait
docker rm -f $TESTNET"bitcoin" > /dev/null 2>&1 || true
